version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"        # your computer port : container port
    volumes:
      - ./instance:/app/instance   # saves the database outside the container
    environment:
      - FLASK_ENV=development
